### PR TITLE
Update Wiimmfi patch ... again

### PR DESCRIPTION
**Pull request by Leseratte10**
I'm terribly sorry, but a bug has been found in the old patcher and we've needed to update them all again...

Making this a draft PR first so it can be tested again ...

### CODE REVIEW

**Comment by DacoTaco** [comment]
aight

**Comment by InternalLoss** [comment]
Connected fine with Mario Kart Wii, SSBB, and PES 2008

**Comment by Leseratte10** [comment]
Okay, I'd say that this should now be ready to be merged. There haven't been any complaints since the last update, so it's probably unlikely that there are still more hidden bugs in the patcher(s). Of course that doesn't necessarily mean there also are no bugs in this Priiloader version (since the loading code is pretty different from the one in the other patchers), but the code that actually performs the updated Wiimmfi patch is almost 1:1 been taken from the other Wiimmfi patcher so I'd say that that's unlikely.

Hopefully this is the last update for a while.

**Comment by FishamanP** [comment]
I couldn't think of a better place to ask this. Does the Wiimmfi Patch v4 apply to only the Disc Channel? Or does it also patch the System Menu, WiiWare, and VC?

**Comment by Leseratte10** [comment]
If I remember correctly it only patches Disk titles, not channel titles (WiiWare, VC, MKW Channel, ...)

**Pull request merged**
