### PR TITLE
reworked the opendolboot.

### PR DESCRIPTION
**Pull request by DacoTaco**
- stopped using the system menu nand bootcode , start using HBC's nand
boot code.
- place nand code at the start of the binary.

with these changes the binaries are bootable as vWii title binaries too.

### CODE REVIEW

**Comment by DacoTaco** [comment]
@Leseratte10 : if you have time, can you check if in linux it processes an .app that is bootable as well?
in windows it works.

**Comment by Leseratte10** [comment]
Sure, I'll do that tomorrow. So does that mean that there's a chance to get Priiloader to work normally on vWii (replacing the system menu) or is that just to be able to start it from the homebrew channel?

**Comment by DacoTaco** [comment]
this is just a cleanup and getting my tools to work on vWii.
it does not , in any way, help me get priiloader in system menu in vWii :/

**Comment by Leseratte10** [comment]
Can confirm that building this branch on Linux results in a working Priiloader.

**Comment by DacoTaco** [comment]
thanks!

**Pull request merged**
