### PR TITLE
Update power & reset button logic so that first RESET is ignored

### PR DESCRIPTION
**Pull request by Leseratte10**
The fix that was applied for #214 (increasing the wait time from 2 seconds to 5 seconds) still didn't work properly in my case, thus I'd like to suggest this change. 

This decreases the wait time back to one second, but makes it so that the very first RESET button press is always ignored, in case it is the very first button press ever. Most of the time, because the wait time is only 1 second, the user will still be holding down the RESET button when this runs, meaning that ignoring it will work perfectly (allowing the user to stay in Priiloader, no matter how long he holds down the RESET switch). 

If the user indeed manages to let go of the RESET switch within 1 second after Priiloader initialized, then the only ill effect would be that the very first RESET press will be ignored, meaning, in that case the user might need to press the RESET button twice to boot into the System menu. If the user were to use POWER to navigate to another menu entry first, that would be no problem (POWER button is always accepted). 

In my opinion, that's a better solution, rather than frustrating users like me who have a TV that takes quite a while to switch to the Wii video input. The only way this could inconvenience someone would be if the user manages to A) let go of the RESET switch within that 1 second frame, and B) if he immediately wants to press RESET again to boot the system menu without navigating to another menu entry. In that particular case, he would need to press RESET again to confirm. I think that's a way better tradeoff than booting someone into the System Menu just because the RESET button was held for a bit too long.

### CODE REVIEW

**Comment by DacoTaco** [comment]
isn't it better to design this like you first suggested? 
that power needs to be pressed to enable front panel input, and then its free game.
you wouldn't need to 'lose' an input and the code would be cleaner too, no?

**Comment by Leseratte10** [comment]
Why would that be better? In its current state, most of the time you wouldn't lose a button at all. Priiloader loads, you are still holding reset, and as soon as you let go of RESET it recognizes the button press and all the buttons are enabled. Only if you manage to let go of the button in the one second after Priiloader started, you'd need to either press POWER or RESET to enable it.

**Comment by DacoTaco** [comment]
just a question : how long does your tv take before it shows the priiloader screen? you can check that by disabling return to in priiloader and boot SM from HBC.

also, did the problem happen more after the keyboard branch?

**Comment by Leseratte10** [comment]
Starting from standby, it takes quite a while until it notices what input port is currently active, thus sometimes when I finally see the priiloader screen it was already "too late" to let go of the button. 

Anyways, I don't think adding that kind of "button lock" would cause that much trouble. I could change it to require a POWER button press to "enable" first if you want to, but that would probably confuse people who just want to start the System Menu and would wonder why pressing RESET doesn't work. The current solution would require you to just push RESET again in case the first time didn't work. 

Or maybe we could just get rid of that 1 second time delay prior to button reading at all?  Then Priiloader should always read the first RESET press, unless the button is being let go in the few ms between Priiloader deciding to boot and Priiloader checking the button for the first time.

**Comment by DacoTaco** [comment]
closing PR.
if my fix didn't work then open a new PR (after rebasing your branch) with a fix of my fix or your own code

**Pull request closed without merging**
