### PR TITLE
Wiimmfi patch v2: Cleanup & security fix

### PR DESCRIPTION
**Pull request by Leseratte10**
Update the Wiimmfi patch to v2. Some cleanup, and a small security fix for yet another stupid Nintendo bug. 

So far I have tested it on 4.3, in all four system menu and disc regions. I'd appreciate if people could test this version with some of the other regions / firmware versions again. 

To everyone: These changes require commit dbe303131e5b2cc73c5db25e68c3f1667258189c to work reliably, so if you want to test the hacks_hash.ini from this PR, please use the Priiloader test build in #254 and NOT Priiloader 0.9 beta 4.

### CODE REVIEW

**Comment by DacoTaco** [comment]
what was this nintendo bug anyway?

**Comment by Leseratte10** [comment]
I'm not sure if it'd be a good idea to make the exact details known yet. Very vaguely, they didn't validate some data (that a user or an attacker could potentially modify) that they really should have validated.

**Comment by Leseratte10** [comment]
Okay, I have now tested all four versions of the 4.3 menu (4.3E, 4.3U, 4.3J, 4.3K) with their corresponding disc region; and they all worked without any problems. 

I didn't test all the other versions (4.1, 4.2, Mini) again, but I did confirm all the offsets again with a calculator so these should all be correct and working as well. I believe this should now be ready to be merged and packaged into beta 5, and then shortly after that it can probably in 0.9 final.

**Comment by Leseratte10** [comment]
There might be yet another security-related fix I need to add to the Wiimmfi patch...
Damn it, when I had the idea for a Priiloader Wiimmfi patch last year I didn't think it would take this long ...

**Comment by DacoTaco** [comment]
i know it probably won't happen, but maybe post the source on some source control so users can review and help you fix all the issues & security issues.

**Pull request merged**
