### PR TITLE
New system menu hack: Block Disc Autoboot

### PR DESCRIPTION
**Pull request by MasterofGalaxies**

### CODE REVIEW

**Comment by DacoTaco** [comment]
mind me asking, disc autoboot? what's that?

**Comment by MasterofGalaxies** [comment]
The system menu autoboots any inserted disc whose ID starts with 0 or 1. An example of a disc that does this is the Movie-Ch Install Disc.

See https://wiibrew.org/wiki/Wii_disc#Methods_to_boot_a_disc and https://wiibrew.org/wiki/Wii_BootMe

**Comment by MasterofGalaxies** [comment]
You can test this by setting the game ID of an ISO to something beginning with a 0 or 1, and then using Dolphin's File -> Change Disc option with the system menu running.

**Comment by DacoTaco** [comment]
huh, i never knew this was a thing. thats cool, thanks !

**Pull request merged**
